# Data path
data:
  train_imgs: "data/mnist-dataset/train-images.idx3-ubyte"
  train_labels: "data/mnist-dataset/train-labels.idx1-ubyte"
  test_imgs: "data/mnist-dataset/t10k-images.idx3-ubyte"
  test_labels: "data/mnist-dataset/t10k-labels.idx1-ubyte"

# Data augmentation
augmentation:
  batch_size: 32
  rotation: 20
  width_shift: 0.2
  height_shift: 0.2
  zoom: 0.2
  shear: 0.1
  fill_mode: "nearest"

# Model
model:
  input_shape: [28, 28, 1]
  num_classes: 10
  path: "./models"

# Training
training:
  learning_rate: 0.0007
  phase1_epochs: 30
  phase2_epochs: 19
  steps_per_epoch: 500
  validation_steps: 100